#!/usr/bin/env python3
"""
BRAIN CORTEX — Central Consciousness
=====================================
The core of the neural architecture. Unlike a pipeline (linear stages passing data forward),
the brain is a network where ALL regions fire simultaneously.

Architecture:
```
                     ┌─────────────────────────────────────┐
                     │         CORTEX (CONSCIOUSNESS)       │
                     │  Central awareness that integrates   │
                     │  ALL inputs simultaneously, decides  │
                     │  what matters, routes to outputs,    │
                     │  learns from results                 │
                     └──────┬──────┬──────┬──────┬──────────┘
                            │      │      │      │
              ┌─────────────┘      │      │      └─────────────┐
              ▼                    ▼      ▼                    ▼
     ┌──────────────┐    ┌──────────────┐    ┌──────────────┐
     │  SENSORY      │    │  ASSOCIATION  │    │  MOTOR       │
     │  CORTEX       │◄──►│  CORTEX      │◄──►│  CORTEX      │
     │  (Inputs)     │    │  (Process)   │    │  (Outputs)   │
     └──────────────┘    └──────────────┘    └──────────────┘
            ▲                    ▲                    ▲
            │                    │                    │
     ┌──────┴──────┐    ┌──────┴──────┐    ┌────────┴────────┐
     │ 12+ crons   │    │ Hippocampus │    │ Bill TS         │
     │ YouTube     │    │ (Memory)    │    │ Gengar          │
     │ arXiv       │    │ Pathways    │    │ Python Arsenal  │
     │ Agent msgs  │    │ (Plasticity)│    │ TradingAgents   │
     └─────────────┘    └─────────────┘    └─────────────────┘
```

Key principles:
1. PARALLEL: All sensory inputs ingested simultaneously, not in stages
2. INTEGRATED: Cortex builds a single awareness map from ALL signals
3. ATTENTION: What's novel or important gets more processing
4. MEMORY: Hippocampus recalls similar past states
5. PLASTICITY: Neural pathways strengthen/weaken based on outcomes
6. EMERGENCE: The whole system is smarter than any individual part

Usage:
  python3 scripts/brain_cortex.py           # Single consciousness cycle
  python3 scripts/brain_cortex.py --daemon  # Continuous (runs every 30m)
  python3 scripts/brain_cortex.py --status  # Show brain state
  python3 scripts/brain_cortex.py --awareness  # Show current awareness map
  python3 scripts/brain_cortex.py --regions     # Show all brain regions
"""

import json
import os
import glob
import hashlib
import subprocess
import sys
import time
from datetime import datetime, timezone, timedelta
from pathlib import Path
from typing import Any, Optional

DEFAULT_ROOT = Path.home() / "hedge" / ".rumbling-hedge"
ROOT = Path(os.path.expanduser(os.environ.get("RH_BRAIN_ROOT", str(DEFAULT_ROOT))))
BRAIN_DIR = ROOT / "brain"
STATE_DIR = ROOT / "state"
LEARNING_DIR = ROOT / "learning"
RESEARCH_DIR = ROOT / "research"

# Defensive signal freshness. Stale signals may remain inspectable in the
# sensory map, but they must not contribute direction or active counts.
DEFAULT_SIGNAL_TTL_SECONDS = 6 * 60 * 60
SIGNAL_TTL_SECONDS = {
    "cot": 10 * 24 * 60 * 60,
    "insider": 24 * 60 * 60,
    "pead": 24 * 60 * 60,
    "noise": 24 * 60 * 60,
    "rolling_window": 24 * 60 * 60,
    "gamma": 24 * 60 * 60,
    "macro": 12 * 60 * 60,
    "alt_data": 12 * 60 * 60,
    "opening_candle": 2 * 60 * 60,
    "manipulation": 8 * 60 * 60,
    "delta_dislocation": 4 * 60 * 60,
}

DYNAMIC_STATE_SUFFIXES = (
    ".latest.json",
    "-signal.json",
)
DYNAMIC_STATE_KEYWORDS = (
    "signal",
    "gate",
    "sizing",
    "arbitration",
    "learning",
    "prediction",
    "backtrader",
    "walkforward",
    "replay",
    "quality",
    "risk",
    "regime",
    "trend",
    "momentum",
)
DYNAMIC_STATE_EXCLUDE_PREFIXES = (
    "bill-",
    "worktree-",
    "source-",
    "codex-",
    "cron-",
)


# ─── NEURAL ARCHITECTURE DEFINITION ────────────────────────────────

BRAIN_REGIONS = {
    "sensory_cortex": {
        "name": "Sensory Cortex",
        "function": "Ingest ALL inputs simultaneously",
        "inputs": [
            # PLAYBOOK — Primary consciousness input (aggregates ALL gate states)
            # Generated by futures_strategy_playbook.py via brain-tick cron (every 15min)
            {"id": "playbook", "source": STATE_DIR / "futures-strategy-playbook.latest.json", "type": "gate"},
            {"id": "market_data", "source": STATE_DIR / "arbitration.latest.json", "type": "signal"},
            {"id": "insider", "source": STATE_DIR / "insider-signal.latest.json", "type": "signal"},
            {"id": "cot", "source": STATE_DIR / "cot-signal.latest.json", "type": "signal"},
            {"id": "ichimoku", "source": STATE_DIR / "ichimoku-signal.latest.json", "type": "signal"},
            {"id": "vwap", "source": STATE_DIR / "vwap-signal.latest.json", "type": "signal"},
            {"id": "kalman", "source": STATE_DIR / "kalman-pairs-signal.latest.json", "type": "signal"},
            {"id": "dom", "source": STATE_DIR / "dom-proxy-signal.latest.json", "type": "signal"},
            {"id": "heiken", "source": STATE_DIR / "heiken-ashi-signal.latest.json", "type": "signal"},
            {"id": "manipulation", "source": STATE_DIR / "manipulation-4h-signal.latest.json", "type": "signal"},
            {"id": "opening_candle", "source": STATE_DIR / "opening-candle-signal.latest.json", "type": "signal"},
            {"id": "donchian", "source": STATE_DIR / "donchian-signal.latest.json", "type": "signal"},
            {"id": "sr_proximity", "source": STATE_DIR / "sr-proximity-signal.latest.json", "type": "signal"},
            {"id": "pead", "source": STATE_DIR / "pead-signal.latest.json", "type": "signal"},
            {"id": "whale", "source": STATE_DIR / "whale-flow-signal.latest.json", "type": "signal"},
            {"id": "noise", "source": STATE_DIR / "noise-analysis.latest.json", "type": "regime"},
            {"id": "fibonacci", "source": STATE_DIR / "fibonacci-signal.latest.json", "type": "signal"},
            {"id": "rolling_window", "source": STATE_DIR / "rolling-window-params.latest.json", "type": "params"},
            # GOLD #6-#11: New signal sources
            {"id": "pm_arb", "source": STATE_DIR / "pm-arb-scanner.latest.json", "type": "signal"},
            {"id": "sentiment", "source": STATE_DIR / "nlp-sentiment.latest.json", "type": "signal"},
            {"id": "execution", "source": STATE_DIR / "execution-optimizer.latest.json", "type": "params"},
            {"id": "macro", "source": STATE_DIR / "macro-trend-overlay.latest.json", "type": "signal"},
            {"id": "alt_data", "source": STATE_DIR / "alt-data-bridge.latest.json", "type": "signal"},
            {"id": "gamma", "source": STATE_DIR / "dealer-gamma-signal.latest.json", "type": "signal"},
            # DOM divergence (delta dislocation)
            {"id": "delta_dislocation", "source": STATE_DIR / "delta-dislocation.latest.json", "type": "signal"},
            # Signal quality improvements (May 29, 2026)
            {"id": "vol_regime_gate", "source": STATE_DIR / "vol-regime-gate.latest.json", "type": "signal"},
            {"id": "microstructure", "source": STATE_DIR / "microstructure-filter.latest.json", "type": "signal"},
            {"id": "failure_rag", "source": STATE_DIR / "failure-rag.latest.json", "type": "signal"},
            {"id": "multitf_confirmation", "source": STATE_DIR / "multitf-confirmation.latest.json", "type": "signal"},
            {"id": "risk_sizing", "source": STATE_DIR / "risk-aware-sizing.latest.json", "type": "params"},
            # Risk engine hardening (May 29, 2026)
            {"id": "circuit_breaker", "source": STATE_DIR / "drawdown-circuit-breaker.latest.json", "type": "gate"},
            {"id": "position_sizing", "source": STATE_DIR / "position-sizing-engine.latest.json", "type": "params"},
        ],
    },
    "association_cortex": {
        "name": "Association Cortex",
        "function": "Process, correlate, fuse signals into awareness",
        "modules": [
            "signal_arbitration → fused direction",
            "multi_d_test_engine → dimensional test plans",
            "research_collector → new content scanning",
            "signal_extractor → gold/silver classification",
            "risk_council → gate before motor (GOLD #2)",
            "portfolio_sizing → contract recommendations (GOLD #4)",
        ],
    },
    "motor_cortex": {
        "name": "Motor Cortex",
        "function": "Route processed awareness to execution engines",
        "outputs": [
            "Bill TS engine (futures)",
            "Gengar (prediction markets)",
            "Python arsenal (signal generators)",
            "TradingAgents (AI debate)",
            "Agent messages (peer-to-peer)",
        ],
    },
    "hippocampus": {
        "name": "Hippocampus (Memory)",
        "function": "Associative memory — recall similar past states",
        "capacity": "Episodic memory, pattern matching, correlation",
    },
    "limbic_system": {
        "name": "Limbic System (Learning)",
        "function": "Reward/punishment — Bayesian source quality + pathway plasticity",
        "mechanism": "WIN → strengthen, LOSS → weaken, NEUTRAL → decay",
    },
    "brain_stem": {
        "name": "Brain Stem (Autonomous)",
        "function": "Kill switch, circadian rhythm, health monitoring",
        "auto": "heartbeat every 5m, kill switch always active",
    },
}


def _signal_id_from_state_file(path: Path) -> str:
    name = path.name
    for suffix in (".latest.json", ".json"):
        if name.endswith(suffix):
            name = name[: -len(suffix)]
            break
    return name.replace("-", "_")


def _looks_like_dynamic_signal(path: Path) -> bool:
    name = path.name
    if any(name.startswith(prefix) for prefix in DYNAMIC_STATE_EXCLUDE_PREFIXES):
        return False
    if not name.endswith(DYNAMIC_STATE_SUFFIXES) and not name.endswith(".json"):
        return False
    return any(keyword in name for keyword in DYNAMIC_STATE_KEYWORDS)


def sensory_inputs() -> list[dict[str, Any]]:
    """Return static sensory inputs plus newly discovered canonical state files."""
    static_inputs = list(BRAIN_REGIONS["sensory_cortex"]["inputs"])
    seen = {str(item["source"]) for item in static_inputs}
    seen_ids = {str(item["id"]) for item in static_inputs}
    discovered = []
    if STATE_DIR.exists():
        for path in sorted(STATE_DIR.iterdir()):
            if not path.is_file() or not _looks_like_dynamic_signal(path):
                continue
            signal_id = _signal_id_from_state_file(path)
            if str(path) in seen or signal_id in seen_ids:
                continue
            discovered.append({
                "id": signal_id,
                "source": path,
                "type": "dynamic_state",
                "dynamic": True,
            })
    return static_inputs + discovered

# Neural pathway weights (strength of connection between regions)
# These evolve over time via plasticity
DEFAULT_PATHWAYS = {
    "sensory→association": 0.8,     # Signals → processing (strong by default)
    "association→motor": 0.7,       # Processing → execution (medium-strong)
    "sensory→motor": 0.3,           # Direct signals → execution (weak — bypasses processing)
    "hippocampus→association": 0.6, # Memory → processing (medium)
    "hippocampus→sensory": 0.4,     # Memory → how we perceive (low-medium)
    "limbic→pathways": 0.9,         # Learning → pathway updates (strong)
    "brain_stem→kill": 1.0,         # Kill switch → block everything (absolute)
    "sensory→hippocampus": 0.7,     # Inputs → memory storage (medium-strong)
    "association→motor_direct": 0.5, # Urgent assoc bypass
}

SYNAPSE_FILE = BRAIN_DIR / "synaptic-weights.json"


ENTROPY_EPSILON = 0.01  # Minimum confidence floor (prevents zero-weight signals)
MUSA_NSR_LOW = 12.0     # Below this = LOW NOISE → strengthen pathways
MUSA_NSR_HIGH = 25.0    # Above this = HIGH NOISE → weaken pathways
MUSA_PATHWAY_BOOST = 0.10   # Max boost fraction for low noise
MUSA_PATHWAY_CUT = 0.15     # Max cut fraction for high noise
ICM_MAX_MEMORY = 3          # Keep last 3 decisions for ICM reflection

# Position awareness (proprioception) — GOLD #1
PROPRIOCEPTION_FILE = ROOT / "state" / "current-position.json"
FUTURES_HEARTBEAT_FILE = ROOT / "state" / "futures-heartbeat.latest.json"
LANE_SEAL_FILE = ROOT / "state" / "live-money-lane-seal.latest.json"
POSITION_INSTRUMENTS = {"NQ": 1.0, "MNQ": 0.5, "ES": 1.0, "MES": 0.5, "CL": 0.8, "GC": 0.8}

# Position-aware attenuation factors
# How much to weaken association→motor when already positioned
SAME_DIR_POSITIONED_1 = 0.70   # 1 contract same direction
SAME_DIR_POSITIONED_2 = 0.45   # 2+ contracts same direction (overconcentrated)
OPP_DIR_POSITIONED   = 1.00    # Opposite position → full strength (flip allowed)
FLAT_COLD            = 0.80    # No recent position, but some uncertainty
FLAT_HOT             = 1.00    # No position, strong signal → full strength
MAX_POSITION_CONTRACTS = 3     # Hard cap: absolute max contracts any single instrument


# ─── CORE FUNCTIONS ────────────────────────────────────────────────

def ensure_dirs():
    BRAIN_DIR.mkdir(parents=True, exist_ok=True)
    (BRAIN_DIR / "cycles").mkdir(parents=True, exist_ok=True)
    (BRAIN_DIR / "awareness").mkdir(parents=True, exist_ok=True)


def load_synaptic_weights() -> dict[str, float]:
    """Load current neural pathway weights, or defaults."""
    if SYNAPSE_FILE.exists():
        try:
            with open(SYNAPSE_FILE) as f:
                return json.load(f)
        except Exception:
            pass
    return dict(DEFAULT_PATHWAYS)


def save_synaptic_weights(weights: dict[str, float]):
    SYNAPSE_FILE.parent.mkdir(parents=True, exist_ok=True)
    with open(SYNAPSE_FILE, "w") as f:
        json.dump(weights, f, indent=2)


# ─── SENSORY CORTEX — Ingest ALL inputs ────────────────────────────

def ingest_all_signals() -> dict[str, Any]:
    """Read ALL signal state files simultaneously. Returns a unified sensory map."""
    sensory = {
        "ts": datetime.now(timezone.utc).isoformat(),
        "signals": {},
        "active_count": 0,
        "total_count": 0,
        "direction_signals": {},  # direction per signal (bullish/bearish/neutral)
        "fused_direction": 0.0,   # -1 to +1
        "regime": "unknown",
        "volatility": "unknown",
        "novel_items": [],
        "warnings": [],
    }

    regions = sensory_inputs()
    sensory["configured_static_count"] = len(BRAIN_REGIONS["sensory_cortex"]["inputs"])
    sensory["dynamic_discovered_count"] = max(0, len(regions) - sensory["configured_static_count"])
    for inp in regions:
        src = inp["source"]
        if not src.exists():
            continue

        try:
            with open(src) as f:
                data = json.load(f)
        except Exception:
            continue

        signal_id = inp["id"]
        stat = src.stat()
        age_seconds = time.time() - stat.st_mtime
        ttl_seconds = SIGNAL_TTL_SECONDS.get(signal_id, DEFAULT_SIGNAL_TTL_SECONDS)
        is_fresh = age_seconds <= ttl_seconds

        # Extract direction. Stale files are retained for diagnostics but are
        # neutralized before fusion so old weekend/holiday outputs cannot fire
        # motor decisions.
        try:
            raw_direction = _extract_direction(signal_id, data)
        except Exception as exc:
            raw_direction = None
            sensory["warnings"].append(f"SIGNAL PARSE ERROR: {signal_id} direction error={exc}")
        direction = raw_direction if is_fresh else None

        # Extract entropy for confidence weighting
        try:
            entropy = _extract_entropy(signal_id, data)
        except Exception as exc:
            entropy = None
            sensory["warnings"].append(f"SIGNAL PARSE ERROR: {signal_id} entropy error={exc}")
        # If entropy unavailable, default to neutral (0.5)
        if entropy is None:
            entropy = 0.5

        # Apply entropy-adjusted confidence: C = ε + (1-ε)(1-H)
        confidence = ENTROPY_EPSILON + (1.0 - ENTROPY_EPSILON) * (1.0 - entropy)
        if not is_fresh:
            confidence = 0.0
            sensory["warnings"].append(
                f"STALE SIGNAL: {signal_id} age={age_seconds/3600:.1f}h ttl={ttl_seconds/3600:.1f}h ignored"
            )

        sensory["signals"][signal_id] = {
            "type": inp["type"],
            "data": data,
            "fresh": stat.st_mtime,
            "age_seconds": round(age_seconds, 1),
            "ttl_seconds": ttl_seconds,
            "is_fresh": is_fresh,
            "direction": direction,
            "raw_direction": raw_direction,
            "entropy": round(entropy, 3),
            "confidence": round(confidence, 3),
        }
        sensory["total_count"] += 1
        if is_fresh:
            sensory["active_count"] += 1

        if direction is not None:
            sensory["direction_signals"][signal_id] = {
                "direction": direction,
                "confidence": confidence,
                "entropy": entropy,
            }

    # Compute entropy-weighted fused direction (MuSA principle)
    # Instead of simple average: Σ (direction_i × confidence_i) / Σ confidence_i
    dir_entries = sensory["direction_signals"]
    if dir_entries:
        weighted_sum = sum(
            e["direction"] * e["confidence"]
            for e in dir_entries.values()
        )
        total_confidence = sum(e["confidence"] for e in dir_entries.values())
        if total_confidence > 0:
            sensory["fused_direction"] = weighted_sum / total_confidence
        else:
            sensory["fused_direction"] = 0.0

        # Store per-signal attribution score (softmax of confidence-weighted)
        attribution_weights = {}
        for sid, entry in dir_entries.items():
            attribution_weights[sid] = abs(entry["direction"]) * entry["confidence"]
        total_attribution = sum(attribution_weights.values()) or 1.0
        sensory["signal_attribution"] = {
            sid: round(w / total_attribution, 4)
            for sid, w in sorted(
                attribution_weights.items(), key=lambda x: x[1], reverse=True
            )
        }
        sensory["top_signals"] = list(sensory["signal_attribution"].keys())[:3]

    return sensory


def _extract_entropy(signal_id: str, data: dict) -> Optional[float]:
    """Extract entropy (uncertainty) from signal data.
    
    Returns None if entropy can't be determined (default to neutral).
    0.0 = completely certain, 1.0 = maximally uncertain.
    """
    if not isinstance(data, dict):
        return None

    # Direct entropy/confidence fields
    if "entropy" in data:
        e = data["entropy"]
        if isinstance(e, (int, float)):
            return max(0.0, min(1.0, float(e)))
    if "confidence" in data:
        c = data["confidence"]
        if isinstance(c, (int, float)):
            # confidence=1.0 → entropy=0.0, confidence=0.0 → entropy=1.0
            return max(0.0, min(1.0, 1.0 - float(c)))

    # Arbitration format — has final_signal_conf
    if "final_signal_conf" in data:
        c = data["final_signal_conf"]
        if isinstance(c, (int, float)):
            return max(0.0, min(1.0, 1.0 - float(c)))

    # Whale flow — has confidence
    if "confidence" in data:
        c = data["confidence"]
        if isinstance(c, (int, float)):
            return max(0.0, min(1.0, 1.0 - float(c)))

    # Noise analysis (direct noise regime metric)
    if signal_id == "noise":
        nsr = data.get("nq_nsr", data.get("nsr", None))
        if nsr is not None and isinstance(nsr, (int, float)):
            # NSR 0-12 → low noise (low entropy), NSR 40+ → extreme (high entropy)
            return max(0.0, min(1.0, float(nsr) / 50.0))

    return None


def _extract_direction(signal_id: str, data: dict) -> Optional[float]:
    """Extract signal direction (-1 to +1) from various signal formats."""
    if not isinstance(data, dict):
        return None

    # Standardized arbitration format
    if "final_dir" in data:
        return data.get("final_dir", 0)

    # Insider format
    if "nq_bias" in data:
        bias = data["nq_bias"]
        return 1.0 if "bullish" in str(bias).lower() else -1.0 if "bearish" in str(bias).lower() else 0.0

    # COT format
    markets = data.get("markets")
    if isinstance(markets, dict) and "NQ" in markets:
        nq = markets["NQ"]
        if isinstance(nq, dict):
            dir_val = nq.get("direction", 0)
            return float(dir_val) if isinstance(dir_val, (int, float)) else 0.0

    # VWAP format
    if "NQ" in data and isinstance(data["NQ"], dict):
        dir_str = data["NQ"].get("direction", "neutral")
        return 1.0 if "long" in str(dir_str).lower() else -1.0 if "short" in str(dir_str).lower() else 0.0

    # Kalman format
    strat = data.get("strategy", "")
    if strat == "ENTRY_LONG":
        return 0.6
    elif strat == "ENTRY_SHORT":
        return -0.6
    elif strat == "EXIT":
        return 0.0
    elif strat == "HOLD":
        return 0.3 if data.get("direction", "").lower() == "long" else -0.3

    # Whale flow
    dir_val = data.get("direction", "neutral")
    conf = float(data.get("confidence", 0.5))
    if "bullish" in str(dir_val).lower():
        return 1.0 * conf
    elif "bearish" in str(dir_val).lower():
        return -1.0 * conf

    # GOLD #6: PM Arbitrage Scanner — total_found > 0 = crypto opportunity
    if signal_id == "pm_arb":
        found = data.get("total_found", 0)
        edge = data.get("max_edge_pct", 0)
        if found > 0 and edge > 0:
            return min(0.4, edge / 100)
        return 0.0

    # GOLD #7: NLP Sentiment — direct -1..+1 field
    if signal_id == "sentiment":
        s = data.get("sentiment", 0)
        return max(-1.0, min(1.0, float(s)))

    # GOLD #9: Macro Trend Overlay — direct -1..+1 macro_direction
    if signal_id == "macro":
        md = data.get("macro_direction", 0)
        conf = data.get("confidence", 0.5)
        return max(-1.0, min(1.0, float(md))) * float(conf)

    # GOLD #10: Alt Data Bridge — direct -1..+1 macro_signal
    if signal_id == "alt_data":
        ms = data.get("macro_signal", 0)
        return max(-1.0, min(1.0, float(ms)))

    # GOLD #11: Dealer Gamma Signal — direct -1..+1 gamma_signal
    if signal_id == "gamma":
        gs = data.get("gamma_signal", 0)
        return max(-1.0, min(1.0, float(gs)))

    # Delta Dislocation — divergence between price and cumulative delta
    if signal_id == "delta_dislocation":
        ds = data.get("delta_signal", 0)
        return max(-1.0, min(1.0, float(ds)))

    # General direction field
    if "direction" in data:
        d = data["direction"]
        if isinstance(d, (int, float)):
            return float(d)

    return None


def check_market_regime() -> dict[str, Any]:
    """Determine current market regime from signals and calendar."""
    regime = {
        "regime": "unknown",
        "confidence": 0.0,
        "opening_type": "unknown",
        "vix_level": None,
        "day_of_week": datetime.now(timezone.utc).strftime("%A"),
        "is_market_open": False,
        "reason": "",
    }

    # Check opening candle classifier
    oc_file = STATE_DIR / "opening-candle-signal.latest.json"
    if oc_file.exists():
        try:
            with open(oc_file) as f:
                od = json.load(f)
            regime["opening_type"] = od.get("session_type", od.get("type", "unknown"))
            regime["regime"] = regime["opening_type"]
            regime["reason"] += f"opening_candle={regime['opening_type']} "
        except Exception:
            pass

    # Check noise analysis
    na_file = STATE_DIR / "noise-analysis.latest.json"
    if na_file.exists():
        try:
            with open(na_file) as f:
                nd = json.load(f)
            regime["volatility"] = nd.get("nq_noise_regime", nd.get("regime", "unknown"))
            regime["reason"] += f"noise={regime['volatility']} "
        except Exception:
            pass

    # Day of week context
    dow = regime["day_of_week"]
    if dow in ("Saturday", "Sunday"):
        regime["is_market_open"] = False
        regime["regime"] = "weekend"
    else:
        regime["is_market_open"] = True

    return regime


# ─── HIPPOCAMPUS — Associative Memory ─────────────────────────────

class Hippocampus:
    """Associative memory — recalls similar past states for pattern matching."""

    def __init__(self):
        self.memory_file = BRAIN_DIR / "hippocampus-memory.jsonl"
        self.memories = []
        self.load()

    def load(self):
        if self.memory_file.exists():
            with open(self.memory_file) as f:
                for line in f:
                    line = line.strip()
                    if line:
                        try:
                            self.memories.append(json.loads(line))
                        except json.JSONDecodeError:
                            continue

    def store(self, awareness: dict, outcome: Optional[str] = None):
        """GOLD #5: Store enriched episodic memory with structured fields."""
        sigs = awareness.get("signals", {})
        proprio = awareness.get("proprioception") or {}
        entry = {
            "ts": awareness.get("ts", datetime.now(timezone.utc).isoformat()),
            "regime": awareness.get("regime", "unknown"),
            "fused_direction": sigs.get("fused_direction", 0.0),
            "active_signals": sigs.get("active", 0),
            "top_signals": sigs.get("top_signals", []),
            "signal_attribution": sigs.get("signal_attribution", {}),
            "novelty_score": awareness.get("memory", {}).get("novelty_score", 0.0),
            "has_positions": proprio.get("has_positions", False),
            "position_summary": {
                k: {"side": v["side"], "qty": v["qty"]}
                for k, v in proprio.get("position_map", {}).items()
            } if proprio.get("has_positions") else {},
            "pathway_weights": dict(awareness.get("pathway_weights", {})),
            "risk_council": awareness.get("risk_council", {}).get("reason", ""),
            "outcome": outcome,
            "memory_id": hashlib.md5(
                (awareness.get("ts", "") + str(time.time())).encode()
            ).hexdigest()[:12],
        }
        with open(self.memory_file, "a") as f:
            f.write(json.dumps(entry) + "\n")
        self.memories.append(entry)

        if len(self.memories) > 1000:
            self.memories = self.memories[-1000:]
            with open(self.memory_file, "w") as f:
                for m in self.memories:
                    f.write(json.dumps(m) + "\n")

        return entry["memory_id"]

    def recall_similar(self, current_awareness: dict, limit: int = 5) -> list[dict]:
        """Find memories similar to current state."""
        if not self.memories:
            return []

        current_regime = current_awareness.get("regime", "unknown")
        current_dir = current_awareness.get("fused_direction", 0.0)

        scored = []
        for m in self.memories:
            score = 0.0
            # Regime match
            if m.get("regime") == current_regime:
                score += 0.5
            # Direction similarity
            dir_diff = abs(m.get("fused_direction", 0) - current_dir)
            if dir_diff < 0.2:
                score += 0.3
            elif dir_diff < 0.5:
                score += 0.1
            # Recent memories weighted higher
            age_hours = 0
            if "ts" in m:
                try:
                    mt = datetime.fromisoformat(m["ts"])
                    age_hours = (datetime.now(timezone.utc) - mt).total_seconds() / 3600
                except Exception:
                    pass
            if age_hours < 24:
                score += 0.2
            elif age_hours < 72:
                score += 0.1

            scored.append((score, m))

        scored.sort(key=lambda x: x[0], reverse=True)
        return [m for s, m in scored[:limit] if s > 0.3]

    # GOLD #5: Structured memory queries
    def query_by_regime(self, regime: str, limit: int = 5) -> list[dict]:
        """Recall memories for a specific market regime."""
        scored = []
        for m in self.memories:
            m_reg = m.get("regime", "")
            if isinstance(m_reg, dict):
                m_reg = m_reg.get("regime", "")
            if m_reg == regime:
                score = 1.0
                if m.get("outcome") == "win":
                    score += 0.5
                elif m.get("outcome") == "loss":
                    score -= 0.3
                scored.append((score, m))
        scored.sort(key=lambda x: x[0], reverse=True)
        return [m for s, m in scored[:limit]]

    def query_by_outcome(self, outcome: str, limit: int = 5) -> list[dict]:
        """Recall memories by outcome (win/loss/neutral)."""
        matches = [m for m in self.memories if m.get("outcome") == outcome]
        matches.sort(key=lambda x: x.get("ts", ""), reverse=True)
        return matches[:limit]

    def query_by_signal(self, signal_id: str, limit: int = 5) -> list[dict]:
        """Recall memories where a specific signal was among top signals."""
        matches = []
        for m in self.memories:
            top = m.get("top_signals", [])
            if signal_id in top:
                matches.append(m)
        matches.sort(key=lambda x: x.get("ts", ""), reverse=True)
        return matches[:limit]


# ─── ASSOCIATION CORTEX — Process sensory into awareness ──────────

def build_awareness(sensory: dict, memory: Hippocampus, proprioception: Optional[dict] = None,
                    icm_reflection: Optional[dict] = None) -> dict:
    """
    The core consciousness function.
    Takes raw sensory input + memory → produces integrated awareness.
    This is where the brain "thinks."

    Proprioception (GOLD #1) provides position awareness — the brain knows
    where it is positioned in the market before making decisions.

    ICM reflection (from Stock-Evol-Instruct) surfaces the last
    decision's outcome as structured context for this cycle.
    """
    awareness = {
        "ts": sensory["ts"],
        "regime": check_market_regime(),
        "signals": {
            "active": sensory["active_count"],
            "total": sensory["total_count"],
            "fused_direction": round(sensory["fused_direction"], 3),
            "direction_breakdown": {
                k: v["direction"] for k, v in sensory.get("direction_signals", {}).items()
            },
            "entropy_breakdown": {
                k: v["entropy"] for k, v in sensory.get("direction_signals", {}).items()
            },
            "confidence_breakdown": {
                k: v["confidence"] for k, v in sensory.get("direction_signals", {}).items()
            },
            "top_signals": sensory.get("top_signals", []),
            "signal_attribution": sensory.get("signal_attribution", {}),
        },
        "attention": [],  # What deserves focus
        "memory": {
            "similar_past_states": [],
            "novelty_score": 0.0,
        },
        "icm_reflection": icm_reflection,  # Last decision + outcome
        "decisions": [],  # What the brain decides to do
        "pathway_weights": load_synaptic_weights(),
        "proprioception": proprioception,  # Position awareness — GOLD #1
        "risk_council": {},  # GOLD #2: Risk council verdict
        "portfolio_sizing": {},  # GOLD #4: Portfolio sizing
        "warnings": list(sensory.get("warnings", [])),
    }

    # 1. Check for novel patterns (attention mechanism)
    similar = memory.recall_similar(sensory)
    awareness["memory"]["similar_past_states"] = similar
    awareness["memory"]["novelty_score"] = 1.0 - (len(similar) / 5.0) if similar else 1.0

    # 2. Apply MuSA dynamic pathway modulation based on market noise regime
    weights = dict(awareness["pathway_weights"])  # Copy
    noise_regime = sensory.get("regime", "")
    noise_entropy = sensory.get("signals", {}).get("noise", {}).get("entropy", 0.5)

    # Use noise analysis NSR if available
    nsr = None
    noise_signal = sensory.get("signals", {}).get("noise", {})
    if isinstance(noise_signal, dict):
        noise_data = noise_signal.get("data", {})
        if isinstance(noise_data, dict):
            nsr = noise_data.get("nq_nsr", noise_data.get("nsr", None))

    if nsr is not None and isinstance(nsr, (int, float)):
        # MuSA: NSR below low threshold = clean market → strengthen pathways
        if nsr < MUSA_NSR_LOW:
            mult = 1.0 + MUSA_PATHWAY_BOOST * (1.0 - nsr / MUSA_NSR_LOW)
            for p in ["sensory→association", "association→motor"]:
                if p in weights:
                    weights[p] = min(0.95, weights[p] * mult)
        # MuSA: NSR above high threshold = noisy market → weaken pathways
        elif nsr > MUSA_NSR_HIGH:
            mult = 1.0 - MUSA_PATHWAY_CUT * min(1.0, (nsr - MUSA_NSR_HIGH) / 25.0)
            for p in ["sensory→association", "association→motor"]:
                if p in weights:
                    weights[p] = max(0.3, weights[p] * mult)
    else:
        # Fallback: use entropy from noise analysis signal
        if noise_entropy > 0.6:
            mult = 1.0 - MUSA_PATHWAY_CUT * (noise_entropy - 0.6) / 0.4
            for p in ["sensory→association", "association→motor"]:
                if p in weights:
                    weights[p] = max(0.3, weights[p] * mult)
        elif noise_entropy < 0.3:
            mult = 1.0 + MUSA_PATHWAY_BOOST * (1.0 - noise_entropy / 0.3)
            for p in ["sensory→association", "association→motor"]:
                if p in weights:
                    weights[p] = min(0.95, weights[p] * mult)

    awareness["pathway_weights"] = weights

    # 2b. POSITION-AWARE PATHWAY MODULATION (Proprioception — GOLD #1)
    # If the brain has active positions, modulate association→motor based on
    # whether the fused signal direction aligns with or opposes the position.
    fd = sensory["fused_direction"]
    proprio = awareness.get("proprioception")
    if proprio and proprio.get("has_positions"):
        pos_map = proprio.get("position_map", {})
        total_exposure = proprio.get("total_exposure", 0.0)
        am_path = weights.get("association→motor", 0.7)
        original_am = am_path

        # Determine if fused direction aligns with or opposes positions
        # Position side: +1 for long, -1 for short
        for instr, info in pos_map.items():
            pos_sign = 1.0 if info["side"] == "long" else -1.0
            qty = info["qty"]

            # Same direction signal → already positioned, weaken
            if pos_sign * fd > 0.15:
                if qty >= 2:
                    mult = SAME_DIR_POSITIONED_2
                    awareness["attention"].append(
                        f"📊 POSITION: {qty} {instr} {info['side'].upper()} — "
                        f"same direction as signal (fd={fd:+.2f}), "
                        f"attenuating ×{mult} (overconcentrated)"
                    )
                else:
                    mult = SAME_DIR_POSITIONED_1
                    awareness["attention"].append(
                        f"📊 POSITION: {qty} {instr} {info['side'].upper()} — "
                        f"same direction as signal, attenuating ×{mult}"
                    )
                weights["association→motor"] = max(0.2, am_path * mult)
                weights["sensory→motor"] = max(0.1, weights.get("sensory→motor", 0.3) * mult)

            # Opposite direction signal → flip possible, full strength or boost
            elif pos_sign * fd < -0.15:
                awareness["attention"].append(
                    f"📊 POSITION: {qty} {instr} {info['side'].upper()} — "
                    f"OPPOSITE direction (fd={fd:+.2f}), flip considered"
                )
                # Allow full strength — OPP_DIR_POSITIONED = 1.0
                weights["association→motor"] = weights.get("association→motor", 0.7) * OPP_DIR_POSITIONED

        # Check total exposure cap
        if total_exposure >= MAX_POSITION_CONTRACTS:
            weights["association→motor"] = max(0.1, weights["association→motor"] * 0.3)
            awareness["warnings"].append(
                f"⚠️ POSITION CAP: Total exposure {total_exposure:.1f} ≥ {MAX_POSITION_CONTRACTS} max. "
                f"association→motor heavily attenuated."
            )

        # Check for consecutive losses — weaken pathways further
        consec_losses = proprio.get("consecutive_losses", 0)
        if consec_losses >= 2:
            weights["association→motor"] = max(0.15, weights["association→motor"] * 0.7)
            awareness["warnings"].append(
                f"⚠️ CONSECUTIVE LOSSES: {consec_losses} in a row — "
                f"further attenuating execution pathways"
            )

        # Log modulation
        if original_am != weights.get("association→motor", 0.7):
            awareness["attention"].append(
                f"📊 PATHWAY MODULATION: association→motor {original_am:.2f}→{weights['association→motor']:.2f}"
            )

    awareness["pathway_weights"] = weights

    # GOLD #2: Risk Council gate
    risk_verdict = run_risk_council(
        awareness.get("proprioception"),
        sensory["fused_direction"],
        weights
    )
    awareness["risk_council"] = risk_verdict
    if risk_verdict.get("block"):
        awareness["warnings"].append(
            f"  RISK COUNCIL BLOCK: {risk_verdict['reason']} ({risk_verdict['severity']})"
        )
        weights["association→motor"] = weights.get("association→motor", 0.7) * 0.1
        weights["sensory→motor"] = weights.get("sensory→motor", 0.3) * 0.1
        awareness["pathway_weights"] = weights
    elif risk_verdict.get("pathway_cut", 1.0) < 1.0:
        weights["association→motor"] = max(0.1, weights.get("association→motor", 0.7) * risk_verdict["pathway_cut"])
        awareness["pathway_weights"] = weights
        awareness["warnings"].append(
            f"  RISK COUNCIL: {risk_verdict['reason']} — cut ×{risk_verdict['pathway_cut']}"
        )

    # GOLD #4: Portfolio-aware position sizing
    portfolio_verdict = compute_portfolio_sizing(
        sensory["fused_direction"],
        awareness.get("proprioception"),
        awareness["regime"].get("regime", "unknown")
    )
    awareness["portfolio_sizing"] = portfolio_verdict
    if portfolio_verdict["recommended_multiplier"] != 1.0:
        awareness["attention"].append(
            f"  PORTFOLIO SIZING: ×{portfolio_verdict['recommended_multiplier']:.2f} "
            f"({portfolio_verdict['reason']})"
        )

    # 3. Generate attention items (what's novel/important)

    # Check fused direction strength
    fd = sensory["fused_direction"]
    if abs(fd) > 0.5:
        awareness["attention"].append(f"STRONG SIGNAL: direction={fd:.2f} ({sensory['active_count']} signals)")
    elif abs(fd) > 0.3:
        awareness["attention"].append(f"MODERATE SIGNAL: direction={fd:.2f}")
    elif sensory["active_count"] > 0 and abs(fd) < 0.15:
        awareness["attention"].append("CONFLICT: signals cancelling to neutral")

    # Check novelty
    if awareness["memory"]["novelty_score"] > 0.7:
        awareness["attention"].append(f"NOVEL STATE: {sensory['active_count']} active signals, regime unfamiliar")

    # Check ICM reflection — surface last decision outcome
    if icm_reflection:
        prev_outcome = icm_reflection.get("outcome", "unknown")
        prev_action = icm_reflection.get("action", "unknown")
        prev_dir = icm_reflection.get("fused_direction", 0)
        if prev_outcome == "win":
            awareness["attention"].append(
                f"ICM: Previous {prev_action} (dir={prev_dir:+.2f}) was WIN — "
                f"reinforcing pathway"
            )
        elif prev_outcome == "loss":
            awareness["attention"].append(
                f"ICM: Previous {prev_action} (dir={prev_dir:+.2f}) was LOSS — "
                f"consider alternative direction"
            )

    # Check regime
    regime_data = awareness["regime"]
    if regime_data.get("is_market_open"):
        awareness["attention"].append(f"MARKET OPEN: {regime_data.get('day_of_week')} "
                                      f"regime={regime_data.get('regime')}")

    # 3. Check pathway health
    for pathway, weight in weights.items():
        if weight < 0.2:
            awareness["warnings"].append(f"WEAK PATHWAY: {pathway} ({weight:.2f})")

    # 4. Generate decisions based on pathway-weighted processing
    sensory_to_assoc = weights.get("sensory→association", 0.8)
    assoc_to_motor = weights.get("association→motor", 0.7)
    sensory_to_motor = weights.get("sensory→motor", 0.3)

    # Strong fused direction + strong sensory→assoc pathway → process deeper
    if abs(fd) > 0.3 and sensory_to_assoc > 0.5:
        awareness["decisions"].append({
            "action": "process_signals",
            "priority": "high" if abs(fd) > 0.5 else "medium",
            "pathway": "sensory→association→motor",
            "strength": sensory_to_assoc * assoc_to_motor,
        })

    # Novelty + weak memory → collect more data
    if awareness["memory"]["novelty_score"] > 0.7:
        awareness["decisions"].append({
            "action": "collect_research",
            "priority": "medium",
            "pathway": "sensory→hippocampus→association",
            "reasoning": "Novel regime, need more datapoints",
        })

    # Check for direct sensory→motor (urgent signals bypass processing)
    if abs(fd) > 0.6 and sensory_to_motor > 0.4:
        awareness["decisions"].append({
            "action": "urgent_execution",
            "priority": "high",
            "pathway": "sensory→motor (bypass)",
            "strength": sensory_to_motor,
        })

    # Limbic feedback check
    kill_pathway = weights.get("brain_stem→kill", 1.0)
    if kill_pathway > 0.5:
        # Check kill switch file
        ks_file = STATE_DIR / "EMERGENCY_STOP"
        if ks_file.exists():
            awareness["decisions"].append({
                "action": "KILL ALL",
                "priority": "critical",
                "pathway": "brain_stem→kill",
                "reasoning": "Emergency stop active",
            })
            awareness["warnings"].append("🚨 KILL SWITCH ACTIVE — all execution blocked")

    return awareness


# ─── MOTOR CORTEX — Route awareness to outputs ────────────────────

def execute_decisions(awareness: dict, memory: Hippocampus, advisory_only: bool = False):
    """
    Execute the brain's decisions by routing to the correct output engines.
    Each decision goes through weighted pathways.
    """
    decisions = awareness.get("decisions", [])
    if not decisions:
        return {"executed": 0, "results": []}

    if advisory_only:
        return {
            "executed": 0,
            "results": [
                {
                    "action": dec.get("action", ""),
                    "status": "advisory_only_skipped",
                    "target": "none",
                }
                for dec in decisions
            ],
        }

    results = []
    for dec in decisions:
        action = dec.get("action", "")
        priority = dec.get("priority", "low")

        if priority == "critical":
            # Kill switch — write to all engines
            results.append({"action": action, "target": "ALL", "status": "blocked"})
            continue

        if action == "process_signals":
            # Route fused direction to motor targets
            fd = awareness["signals"]["fused_direction"]
            strength = dec.get("strength", 0.5)

            motor_output = {
                "ts": awareness["ts"],
                "fused_direction": fd,
                "strength": strength,
                "regime": awareness["regime"].get("regime", "unknown"),
                "active_signals": awareness["signals"].get("active", 0),
                "direction_breakdown": awareness["signals"]["direction_breakdown"],
                "entropy_breakdown": awareness["signals"].get("entropy_breakdown", {}),
                "confidence_breakdown": awareness["signals"].get("confidence_breakdown", {}),
                "top_signals": awareness["signals"].get("top_signals", []),
                "signal_attribution": awareness["signals"].get("signal_attribution", {}),
                "proprioception": _summarize_proprioception(
                    awareness.get("proprioception")
                ),
            }

            # Write motor output for all engines to read
            motor_file = BRAIN_DIR / "motor-output.latest.json"
            with open(motor_file, "w") as f:
                json.dump(motor_output, f, indent=2)

            results.append({
                "action": action,
                "target": "motor-output.latest.json",
                "direction": fd,
                "strength": strength,
            })

        elif action == "collect_research":
            # Signal that brain wants more research
            hunger_file = BRAIN_DIR / "research-hunger.json"
            with open(hunger_file, "w") as f:
                json.dump({
                    "ts": awareness["ts"],
                    "hunger_level": awareness["memory"]["novelty_score"],
                    "reason": "Novel regime detected, need more datapoints",
                }, f, indent=2)
            results.append({"action": action, "target": "research-hunger.json"})

        elif action == "urgent_execution":
            # Bypass normal processing — send directly to execution
            fd = awareness["signals"]["fused_direction"]
            urgent_file = BRAIN_DIR / "urgent-execution.json"
            with open(urgent_file, "w") as f:
                json.dump({
                    "ts": awareness["ts"],
                    "direction": fd,
                    "reason": "urgent_signal_bypass",
                    "signals": awareness["signals"]["direction_breakdown"],
                }, f, indent=2)
            results.append({
                "action": action,
                "target": "urgent-execution.json",
                "direction": fd,
            })

    # Store the cycle in hippocampus
    memory.store(awareness, outcome=None)

    return {"executed": len(results), "results": results}


# ─── AWARENESS REPORTS

def load_position_state() -> dict:
    """Load current positions from all sources. Returns a unified position map.

    This is the brain's proprioception — awareness of where it is positioned.
    Reads from: current-position.json, futures-heartbeat.json, lane-seal.
    Each entry: {instrument, side, quantity, entry_price, strategy, age_seconds}
    """
    state = {
        "ts": datetime.now(timezone.utc).isoformat(),
        "positions": [],         # Active positions list
        "position_map": {},       # {instrument: {side, qty, avg_entry}}
        "total_exposure": 0.0,   # Sum of |qty| × weight per instrument
        "gross_notional": 0.0,   # Approximate dollar exposure
        "has_positions": False,
        "nq_daily_pnl": 0.0,
        "daily_trade_count": 0,
        "consecutive_losses": 0,
        "live_mode": False,
        "mode": "paper",
    }

    # 1. Read current-position.json (active futures position)
    try:
        cp = json.loads(PROPRIOCEPTION_FILE.read_text())
        pos = {
            "instrument": cp.get("symbol", "?"),
            "side": "long" if cp.get("side", "").startswith("buy") else "short",
            "quantity": int(cp.get("quantity", 0)),
            "entry_price": float(cp.get("entryPrice", 0)),
            "strategy": cp.get("strategyId", "?"),
            "source": "current-position.json",
        }
        # Calculate age
        try:
            pos_ts = cp.get("ts", "")
            if pos_ts:
                pt = datetime.fromisoformat(pos_ts.replace("Z", "+00:00"))
                pos["age_seconds"] = (datetime.now(timezone.utc) - pt).total_seconds()
            else:
                pos["age_seconds"] = 999999
        except Exception:
            pos["age_seconds"] = 999999

        # Only include if fresh enough (less than 6 hours old) and quantity > 0
        if pos["age_seconds"] < 21600 and pos["quantity"] > 0:
            state["positions"].append(pos)
    except (FileNotFoundError, json.JSONDecodeError, KeyError, ValueError):
        pass

    # 2. Read futures-heartbeat for daily PnL, trade counts, lock state
    try:
        fhb = json.loads(FUTURES_HEARTBEAT_FILE.read_text())
        daily = fhb.get("nqDailyLock", {})
        state["nq_daily_pnl"] = float(daily.get("dailyPnL", 0))
        state["daily_trade_count"] = int(daily.get("tradeCount", 0))
        state["consecutive_losses"] = int(daily.get("consecutiveLosses", 0))
    except (FileNotFoundError, json.JSONDecodeError):
        pass

    # 3. Read lane-seal for execution mode
    try:
        ls = json.loads(LANE_SEAL_FILE.read_text())
        state["live_mode"] = bool(ls.get("liveExecution", False))
        state["mode"] = ls.get("mode", "paper")
    except (FileNotFoundError, json.JSONDecodeError):
        pass

    # Build position_map: {instrument: {side, qty, avg_entry}}
    pos_map = {}
    for pos in state["positions"]:
        instr = pos["instrument"]
        norm = instr.upper()
        side = pos["side"]
        qty = pos["quantity"]
        price = pos["entry_price"]

        if norm in pos_map:
            existing = pos_map[norm]
            # Weighted average entry if same side, cancel if opposite
            if existing["side"] == side:
                total = existing["qty"] + qty
                existing["avg_entry"] = (existing["avg_entry"] * existing["qty"] + price * qty) / total
                existing["qty"] = total
            else:
                # Opposite sides partially offset
                net = existing["qty"] - qty
                if net > 0:
                    existing["qty"] = net
                elif net < 0:
                    existing["side"] = side
                    existing["qty"] = abs(net)
                    existing["avg_entry"] = price
                else:
                    # Fully offset — remove
                    del pos_map[norm]
                    continue
        else:
            pos_map[norm] = {"side": side, "qty": qty, "avg_entry": price, "instruments": [instr]}

    state["position_map"] = pos_map

    # Calculate total exposure
    total_exposure = 0.0
    gross_notional = 0.0
    for instr, info in pos_map.items():
        weight = POSITION_INSTRUMENTS.get(instr, 0.5)
        total_exposure += info["qty"] * weight
        gross_notional += info["qty"] * abs(info.get("avg_entry", 0))
    state["total_exposure"] = total_exposure
    state["gross_notional"] = gross_notional
    state["has_positions"] = len(pos_map) > 0

    return state


# ─── GOLD #2: RISK COUNCIL ─────────────────────────────────────────

def run_risk_council(proprioception: Optional[dict], fused_direction: float, pathway_weights: dict) -> dict:
    """Gate signals before motor execution.
    
    Primary: reads drawdown-circuit-breaker.latest.json for tier-based gating.
    Fallback: hardcoded thresholds from proprioception (legacy path).
    Also reads position-sizing-engine.latest.json for contract limits.
    
    Returns: {block: bool, reason: str, severity: str, pathway_cut: float,
              tier: str, max_contracts: int, sizing_multiplier: float}
    """
    result = {
        "block": False, "reason": "", "severity": "", "pathway_cut": 1.0,
        "tier": "UNKNOWN", "max_contracts": 3, "sizing_multiplier": 1.0,
    }

    # 1. Check kill switch file (always first)
    ks_file = STATE_DIR / "EMERGENCY_STOP"
    if ks_file.exists():
        return {
            "block": True, "reason": "EMERGENCY_STOP active", "severity": "critical",
            "pathway_cut": 0.0, "tier": "BLACK", "max_contracts": 0, "sizing_multiplier": 0.0,
        }

    # 2. Read circuit breaker state (primary source of truth)
    breaker_file = STATE_DIR / "drawdown-circuit-breaker.latest.json"
    breaker = None
    if breaker_file.exists():
        try:
            breaker = json.loads(breaker_file.read_text())
        except (json.JSONDecodeError, OSError):
            pass

    if breaker:
        tier = breaker.get("tier", "GREEN")
        mult = breaker.get("sizing_multiplier", 1.0)
        max_c = breaker.get("max_contracts", 3)
        reason = breaker.get("reason", "")
        cooldown = breaker.get("cooldown_active", False)
        cooldown_msg = breaker.get("cooldown_reason", "")

        result["tier"] = tier
        result["sizing_multiplier"] = mult
        result["max_contracts"] = max_c
        result["reason"] = reason

        # Tier-based gating
        if tier == "BLACK":
            result["block"] = True
            result["severity"] = "critical"
            result["pathway_cut"] = 0.0
            result["reason"] = f"BLACK: {reason}"
            return result

        if tier == "RED":
            result["block"] = True
            result["severity"] = "high"
            result["pathway_cut"] = 0.0
            result["reason"] = f"RED: {reason}"
            return result

        if tier == "ORANGE":
            result["severity"] = "medium"
            result["pathway_cut"] = min(result["pathway_cut"], mult)
            result["reason"] = f"ORANGE: {reason}"

        elif tier == "YELLOW":
            result["severity"] = "low"
            result["pathway_cut"] = min(result["pathway_cut"], mult)
            result["reason"] = f"YELLOW: {reason}"

        # Cooldown overrides even GREEN
        if cooldown:
            result["block"] = True
            result["severity"] = "medium"
            result["pathway_cut"] = 0.0
            result["reason"] = f"Cooldown: {cooldown_msg}"
            return result

    # 3. Read position sizing engine for contract recommendations
    sizing_file = STATE_DIR / "position-sizing-engine.latest.json"
    if sizing_file.exists():
        try:
            sizing = json.loads(sizing_file.read_text())
            rec = sizing.get("recommended_contracts", 0)
            gate = sizing.get("gates", {})
            if gate.get("confidence_gate", "") != "pass":
                result["reason"] = (result["reason"] + f" | sizing: {gate['confidence_gate']}").strip(" |")
        except (json.JSONDecodeError, OSError):
            pass

    # 4. Fallback: legacy checks when breaker unavailable
    if not breaker and proprioception:
        consec = proprioception.get("consecutive_losses", 0)
        if consec >= 3:
            result["block"] = True
            result["reason"] = f"3+ consecutive losses ({consec})"
            result["severity"] = "high"
            result["pathway_cut"] = 0.0
        elif consec >= 2:
            result["reason"] = f"{consec} consecutive losses"
            result["severity"] = "medium"
            result["pathway_cut"] = 0.5

        daily_pnl = proprioception.get("nq_daily_pnl", 0)
        if daily_pnl <= -500:
            result["block"] = True
            result["reason"] = f"Daily loss limit (PnL={daily_pnl:.0f})"
            result["severity"] = "high"
            result["pathway_cut"] = 0.0
        elif daily_pnl <= -300:
            result["reason"] = f"Near loss limit (PnL={daily_pnl:.0f})"
            result["severity"] = "medium"
            result["pathway_cut"] = 0.4

        exposure = proprioception.get("total_exposure", 0)
        if exposure >= 3:
            result["block"] = True
            result["reason"] = f"Position cap ({exposure:.1f})"
            result["severity"] = "high"
            result["pathway_cut"] = 0.0
        elif exposure >= 2:
            result["reason"] = f"High exposure ({exposure:.1f})"
            result["severity"] = "medium"
            result["pathway_cut"] = 0.5

    # 5. Overtrading guard (applies regardless of breaker)
    if proprioception:
        trades = proprioception.get("daily_trade_count", 0)
        if trades >= 5:
            result["reason"] = (result["reason"] + f" + {trades} trades").strip(" +")
            result["severity"] = result.get("severity") or "low"
            result["pathway_cut"] = min(result.get("pathway_cut", 1.0), 0.7)

    # 6. Signal too weak
    if abs(fused_direction) < 0.1:
        result["reason"] = (result["reason"] + " | Signal too weak").strip(" |")
        result["severity"] = result.get("severity") or "low"
        result["pathway_cut"] = min(result.get("pathway_cut", 1.0), 0.3)

    return result


# ─── GOLD #4: PORTFOLIO SIZING ──────────────────────────────────────

def compute_portfolio_sizing(fused_direction: float, proprioception: Optional[dict], regime: str) -> dict:
    """Multi-instrument portfolio sizing.
    
    Adjusts contract size based on: correlated risk, trade count,
    consecutive losses, regime conditions.
    """
    sizing = {"recommended_multiplier": 1.0, "reason": "standard", "max_contracts": 2}

    if not proprioception:
        return sizing

    pos_map = proprioception.get("position_map", {})
    same_dir_count = 0
    for instr, info in pos_map.items():
        pos_sign = 1.0 if info["side"] == "long" else -1.0
        if pos_sign * fused_direction > 0.15:
            same_dir_count += info["qty"]

    if same_dir_count >= 2:
        sizing["recommended_multiplier"] = 0.6
        sizing["reason"] = f"Already {same_dir_count} units same direction"
    elif same_dir_count >= 1:
        sizing["recommended_multiplier"] = 0.8
        sizing["reason"] = "Already positioned same direction"

    daily_trades = proprioception.get("daily_trade_count", 0)
    if daily_trades >= 4:
        sizing["recommended_multiplier"] *= 0.6
        sizing["reason"] += f" + {daily_trades} trades"
    elif daily_trades >= 2:
        sizing["recommended_multiplier"] *= 0.85

    consec = proprioception.get("consecutive_losses", 0)
    if consec >= 2:
        sizing["recommended_multiplier"] *= 0.5
        sizing["reason"] += f" + {consec} losses"

    if regime in ("range_chop", "high_vol"):
        sizing["recommended_multiplier"] *= 0.75
        sizing["reason"] += f" + {regime}"
    elif regime in ("trend_day", "gap_up", "gap_down"):
        sizing["recommended_multiplier"] *= 1.1
        sizing["reason"] += f" + {regime} boost"

    sizing["recommended_multiplier"] = max(0.1, min(2.0, sizing["recommended_multiplier"]))
    sizing["max_contracts"] = max(1, int(3 * sizing["recommended_multiplier"]))
    return sizing


# ─── GOLD #3: REGIME-AWARE PLASTICITY ──────────────────────────────

def update_pathways(outcome: str, strength: float = 0.1, regime: str = "unknown"):
    """Regime-aware synaptic plasticity.
    
    WIN/LOSS effects depend on market regime:
    - trend_day: extra strengthen/weaken for trend-following
    - range_chop: different tuning for mean-reversion
    - high_vol: extra cautious adjustments
    """
    weights = load_synaptic_weights()
    regime_mult = {"trend_day": 1.5, "range_chop": 0.7, "high_vol": 1.3,
                   "low_vol": 1.0, "gap_up": 1.2, "gap_down": 1.2,
                   "unknown": 1.0, "weekend": 0.5}
    mult = regime_mult.get(regime, 1.0)

    if outcome == "win":
        for p in ["sensory→association", "association→motor", "hippocampus→association"]:
            if p in weights:
                weights[p] = min(1.0, weights[p] + strength * 0.1 * mult)
        if regime in ("trend_day", "gap_up", "gap_down"):
            if "association→motor" in weights:
                weights["association→motor"] = min(1.0, weights["association→motor"] + strength * 0.15 * mult)
        elif regime == "range_chop":
            if "hippocampus→association" in weights:
                weights["hippocampus→association"] = min(1.0, weights["hippocampus→association"] + strength * 0.15 * mult)

    elif outcome == "loss":
        for p in ["association→motor", "sensory→motor"]:
            if p in weights:
                weights[p] = max(0.1, weights[p] - strength * 0.15 * mult)
        if "limbic→pathways" in weights:
            weights["limbic→pathways"] = min(1.0, weights["limbic→pathways"] + strength * 0.1 * mult)

    elif outcome == "neutral":
        for p in weights:
            if p not in ("brain_stem→kill", "limbic→pathways"):
                weights[p] = max(0.1, weights[p] - 0.01 * mult)

    save_synaptic_weights(weights)
    return weights


# ─── AWARENESS REPORTS ────────────────────────────────────────────

def _summarize_proprioception(proprio: Optional[dict]) -> dict:
    """Build a compact position summary for the awareness report."""
    if not proprio:
        return {"has_positions": False}
    return {
        "has_positions": proprio.get("has_positions", False),
        "positions": {
            k: {"side": v["side"], "qty": v["qty"]}
            for k, v in proprio.get("position_map", {}).items()
        } if proprio.get("has_positions") else {},
        "total_exposure": round(proprio.get("total_exposure", 0.0), 2),
        "daily_pnl": proprio.get("nq_daily_pnl", 0),
        "daily_trades": proprio.get("daily_trade_count", 0),
        "consecutive_losses": proprio.get("consecutive_losses", 0),
        "mode": proprio.get("mode", "paper"),
    }


def write_awareness_summary(awareness: dict):
    """Write human-readable awareness summary for agents to read."""
    summary_file = BRAIN_DIR / "awareness" / "current.json"
    summary_file.parent.mkdir(parents=True, exist_ok=True)

    summary = {
        "ts": awareness["ts"],
        "regime": awareness["regime"].get("regime", "unknown"),
        "day": awareness["regime"].get("day_of_week", "unknown"),
        "market_open": awareness["regime"].get("is_market_open", False),
        "signals_active": awareness["signals"]["active"],
        "fused_direction": awareness["signals"]["fused_direction"],
        "top_signals": awareness["signals"].get("top_signals", []),
        "signal_attribution": awareness["signals"].get("signal_attribution", {}),
        "attention_items": len(awareness["attention"]),
        "decisions": len(awareness["decisions"]),
        "novelty": round(awareness["memory"]["novelty_score"], 2),
        "warnings": awareness["warnings"],
        "proprioception": _summarize_proprioception(
            awareness.get("proprioception")
        ),
        "researchOnly": True,
        "writesOrders": False,
        "touchesBroker": False,
        "tradable_signal": False,
        "promoted_for_execution": False,
        "readyForExecution": False,
        "execution_role": "diagnostic_only",
    }

    with open(summary_file, "w") as f:
        json.dump(summary, f, indent=2)

    return summary


# ─── ICM OUTCOME UPDATE ────────────────────────────────────────────

def update_icm_outcome(outcome: str, cycle_id: Optional[str] = None):
    """Update the ICM reflection with a trade outcome (win/loss/neutral).

    Call this externally when trade results come in.
    Updates the latest un-outcomed ICM entry.
    """
    icm_file = BRAIN_DIR / "icm-reflection.latest.json"
    if not icm_file.exists():
        print("  No ICM reflection to update")
        return False

    try:
        with open(icm_file) as f:
            ref = json.load(f)
    except Exception:
        return False

    ref["outcome"] = outcome
    with open(icm_file, "w") as f:
        json.dump(ref, f, indent=2)

    # Also update in history
    old_icm_file = BRAIN_DIR / "icm-history.jsonl"
    if old_icm_file.exists():
        entries = []
        try:
            with open(old_icm_file) as f:
                for line in f:
                    line = line.strip()
                    if line:
                        try:
                            entry = json.loads(line)
                            if entry.get("outcome") is None:
                                if cycle_id is None or entry.get("cycle_id") == cycle_id:
                                    entry["outcome"] = outcome
                            entries.append(entry)
                        except json.JSONDecodeError:
                            entries.append({"raw": line})
        except Exception:
            pass

        with open(old_icm_file, "w") as f:
            for entry in entries:
                f.write(json.dumps(entry) + "\n")

    print(f"     ICM outcome updated: {outcome}")
    return True


# ─── FULL CYCLE ────────────────────────────────────────────────────

def run_cycle(advisory_only: bool = False) -> dict:
    """
    One complete brain consciousness cycle.
    1. Sensory cortex ingests ALL inputs
    2. Hippocampus recalls similar past states
    3. Load ICM reflection (last decision outcome)
    4. Proprioception: load current positions (GOLD #1 position awareness)
    5. Association cortex builds integrated awareness (with position modulation)
    6. Motor cortex executes decisions
    7. Write awareness for other agents
    8. Store ICM reflection for next cycle
    """
    ensure_dirs()
    start = time.time()

    print(f"\n  🧠 BRAIN CONSCIOUSNESS CYCLE — {datetime.now(timezone.utc).strftime('%H:%M:%S')} UTC")

    # Step 1: Sensory ingestion (parallel)
    sensory = ingest_all_signals()
    print(f"     Sensory: {sensory['active_count']}/{sensory['total_count']} signals active, "
          f"fused dir={sensory['fused_direction']:.3f}")
    if sensory.get("top_signals"):
        print(f"     Top signals: {', '.join(sensory['top_signals'])}")

    # Step 2: Memory recall
    memory = Hippocampus()
    similar = memory.recall_similar(sensory)
    print(f"     Memory: {len(similar)} similar past states recalled (novelty={1.0 - len(similar)/5:.2f})")

    # Step 2b: Load ICM reflection (last decision + outcome)
    icm_file = BRAIN_DIR / "icm-reflection.latest.json"
    icm_reflection = None
    if icm_file.exists():
        try:
            with open(icm_file) as f:
                icm_reflection = json.load(f)
            print(f"     ICM: Last action='{icm_reflection.get('action', '?')}' "
                  f"outcome='{icm_reflection.get('outcome', '?')}'")
        except Exception:
            pass

    # Step 2c: Proprioception — load position awareness (GOLD #1)
    proprioception = load_position_state()
    if proprioception.get("has_positions"):
        pos_str = ", ".join(
            f"{v['qty']} {k} {v['side'].upper()}"
            for k, v in proprioception.get("position_map", {}).items()
        )
        print(f"     Proprioception: Active positions — {pos_str}")
    elif proprioception.get("daily_trade_count", 0) > 0:
        print(f"     Proprioception: No positions today. "
              f"Daily: {proprioception['daily_trade_count']} trades, "
              f"PnL={proprioception['nq_daily_pnl']:+.2f}, "
              f"{proprioception['consecutive_losses']} consecutive losses")
    else:
        print(f"     Proprioception: No active positions")

    # Step 3: Association (build awareness with ICM reflection + proprioception)
    awareness = build_awareness(sensory, memory, proprioception=proprioception,
                                icm_reflection=icm_reflection)
    print(f"     Association: {len(awareness['attention'])} attention items, "
          f"{len(awareness['warnings'])} warnings")
    if awareness.get("icm_reflection"):
        print(f"     ICM reflection: {awareness['icm_reflection'].get('outcome', 'none')}")

    # Step 4: Motor execution
    motor_result = execute_decisions(awareness, memory, advisory_only=advisory_only)
    print(f"     Motor: {motor_result['executed']} decisions executed")

    # Step 5: Write awareness
    summary = write_awareness_summary(awareness)

    # Step 6: Store ICM reflection for next cycle
    # This keeps a rolling window of the last few decisions
    icm_entries = []
    old_icm_file = BRAIN_DIR / "icm-history.jsonl"
    if old_icm_file.exists():
        try:
            with open(old_icm_file) as f:
                for line in f:
                    line = line.strip()
                    if line:
                        try:
                            icm_entries.append(json.loads(line))
                        except json.JSONDecodeError:
                            pass
        except Exception:
            pass

    # Add this cycle's decision
    for dec in awareness.get("decisions", []):
        icm_entry = {
            "ts": awareness["ts"],
            "cycle_id": datetime.now(timezone.utc).strftime("cycle_%Y%m%d_%H%M%S"),
            "action": dec.get("action", ""),
            "priority": dec.get("priority", ""),
            "pathway": dec.get("pathway", ""),
            "fused_direction": sensory.get("fused_direction", 0),
            "top_signals": sensory.get("top_signals", []),
            "regime": awareness["regime"].get("regime", "unknown"),
            "outcome": None,  # Will be filled when trade result arrives
        }
        icm_entries.append(icm_entry)

    # Keep only last ICM_MAX_MEMORY entries
    icm_entries = icm_entries[-ICM_MAX_MEMORY:]

    # Write latest reflection (most recent decision)
    if icm_entries:
        with open(icm_file, "w") as f:
            json.dump(icm_entries[-1], f, indent=2)

    # Append to history
    with open(old_icm_file, "w") as f:
        for entry in icm_entries:
            f.write(json.dumps(entry) + "\n")

    # Save cycle
    cycle_id = datetime.now(timezone.utc).strftime("cycle_%Y%m%d_%H%M%S")
    cycle_file = BRAIN_DIR / "cycles" / f"{cycle_id}.json"
    with open(cycle_file, "w") as f:
        json.dump({
            "ts": sensory["ts"],
            "sensory": {k: v for k, v in sensory.items()
                        if k in ("active_count", "total_count", "fused_direction",
                                 "top_signals", "signal_attribution")},
            "awareness_summary": summary,
            "decisions": awareness["decisions"],
            "icm_reflection": icm_reflection,
            "musa_pathway_modulation": {
                "pathway_weights": awareness["pathway_weights"],
            },
            "duration_s": round(time.time() - start, 2),
            "advisoryOnly": advisory_only,
            "motor_result": motor_result,
            "researchOnly": True,
            "writesOrders": False,
            "touchesBroker": False,
        }, f, indent=2)

    # Also write current brain state
    brain_state_file = BRAIN_DIR / "brain-state.latest.json"
    with open(brain_state_file, "w") as f:
        json.dump({
            "ts": sensory["ts"],
            "cycle_id": cycle_id,
            "fused_direction": sensory["fused_direction"],
            "entropy_weighted": True,
            "active_signals": sensory["active_count"],
            "top_signals": sensory.get("top_signals", []),
            "regime": awareness["regime"],
            "novelty": awareness["memory"]["novelty_score"],
            "pathway_weights": awareness["pathway_weights"],
            "icm_reflection": icm_reflection,
            "proprioception": _summarize_proprioception(
                awareness.get("proprioception")
            ),
            "researchOnly": True,
            "writesOrders": False,
            "touchesBroker": False,
            "tradable_signal": False,
            "promoted_for_execution": False,
            "readyForExecution": False,
            "execution_role": "diagnostic_only",
            "advisoryOnly": advisory_only,
            "attention": awareness["attention"][:3],
            "decisions": awareness["decisions"][:3],
            "warnings": awareness["warnings"],
        }, f, indent=2)

    print(f"     Cycle complete in {time.time()-start:.1f}s")

    return awareness


# ─── CLI ───────────────────────────────────────────────────────────

def cmd_cycle(advisory_only: bool = False):
    """Run a single consciousness cycle."""
    awareness = run_cycle(advisory_only=advisory_only)
    print(f"\n  📋 Current Awareness:")
    print(f"     {'Regime:':18s} {awareness['regime'].get('regime', '?')} "
          f"({awareness['regime'].get('day_of_week', '?')})")
    print(f"     {'Signals:':18s} {awareness['signals']['active']} active, "
          f"fused direction={awareness['signals']['fused_direction']:+.3f} "
          f"(entropy-weighted)")
    print(f"     {'Top signals:':18s} {', '.join(awareness['signals'].get('top_signals', ['none']))}")
    print(f"     {'Novelty:':18s} {awareness['memory']['novelty_score']:.2f}")
    if awareness.get("icm_reflection"):
        ir = awareness["icm_reflection"]
        print(f"     {'ICM:':18s} Last {ir.get('action','?')} → {ir.get('outcome','?')} "
              f"(dir={ir.get('fused_direction',0):+.2f})")
    if awareness['attention']:
        print(f"     {'Attention:':18s}")
        for a in awareness['attention'][:5]:
            print(f"       • {a}")


def cmd_status():
    """Show brain state."""
    brain_file = BRAIN_DIR / "brain-state.latest.json"
    weights = load_synaptic_weights()
    cycles = list(sorted((BRAIN_DIR / "cycles").glob("cycle_*.json"))) if (BRAIN_DIR / "cycles").exists() else []
    memory_file = BRAIN_DIR / "hippocampus-memory.jsonl"
    mem_count = sum(1 for _ in open(memory_file)) if memory_file.exists() else 0

    print(f"\n{'='*60}")
    print(f"  🧠 BRAIN STATE")
    print(f"{'='*60}")

    if brain_file.exists():
        with open(brain_file) as f:
            state = json.load(f)
        print(f"\n  Current consciousness:")
        print(f"     Fused direction: {state.get('fused_direction', 0):+.3f}")
        print(f"     Regime: {state.get('regime', {}).get('regime', '?')}")
        print(f"     Novelty: {state.get('novelty', 0):.2f}")
        for a in state.get("attention", []):
            print(f"     🔔 {a}")

    print(f"\n  Regions:")
    for region_id, region in BRAIN_REGIONS.items():
        print(f"     🧠 {region['name']}")
        print(f"        ├ {region['function']}")

    print(f"\n  Neural pathways:")
    for pathway, weight in sorted(weights.items()):
        bar = "█" * int(weight * 20) + "░" * (20 - int(weight * 20))
        status = "🟢" if weight > 0.6 else "🟡" if weight > 0.3 else "🔴"
        print(f"     {status} {pathway:<25s} {bar} {weight:.2f}")

    print(f"\n  Memory: {mem_count} episodic memories stored")
    print(f"  Cycles: {len(cycles)} total")
    if cycles:
        print(f"  Last cycle: {cycles[-1].stem}")

    print()


def cmd_awareness():
    """Show current awareness report."""
    aw_file = BRAIN_DIR / "awareness" / "current.json"
    if not aw_file.exists():
        print("  No awareness data. Run a cycle first.")
        return

    with open(aw_file) as f:
        aw = json.load(f)

    print(f"\n{'='*60}")
    print(f"  CURRENT AWARENESS — {aw.get('ts', '?')[:19]}")
    print(f"{'='*60}")
    market = "🟢 OPEN" if aw.get("market_open") else "🔴 CLOSED"
    print(f"  {market} | {aw.get('day', '?')} | Regime: {aw.get('regime', '?')}")
    print(f"  Signals: {aw.get('signals_active', 0)} active | "
          f"Direction: {aw.get('fused_direction', 0):+.3f} | "
          f"Novelty: {aw.get('novelty', 0):.2f}")
    if aw.get("warnings"):
        print(f"\n  ⚠️  Warnings:")
        for w in aw["warnings"]:
            print(f"     {w}")
    print()


def cmd_daemon():
    """Continuous mode — runs every 30 minutes."""
    print(f"\n  🧠 BRAIN DAEMON STARTED — running every 30m in advisory-only mode")
    print(f"     Press Ctrl+C to stop\n")

    while True:
        run_cycle(advisory_only=True)
        print(f"\n  💤 Sleeping 30 minutes...")
        time.sleep(1800)


def main():
    import argparse
    parser = argparse.ArgumentParser(
        description="🧠 Brain Cortex — Central consciousness for the trading system"
    )
    parser.add_argument("action", nargs="?", default="cycle",
                        choices=["cycle", "daemon", "status", "awareness", "regions",
                                 "update-outcome", "memory"],
                        help="Brain action (default: cycle)")
    parser.add_argument("--outcome", type=str, default=None,
                        help="Outcome for update-outcome: win/loss/neutral")
    parser.add_argument("--cycle-id", type=str, default=None,
                        help="Cycle ID for update-outcome")
    parser.add_argument("--regime", type=str, default=None,
                        help="Regime filter for memory query")
    parser.add_argument("--signal", type=str, default=None,
                        help="Signal filter for memory query")
    parser.add_argument("--limit", type=int, default=5,
                        help="Limit for memory query")
    parser.add_argument("--advisory-only", action="store_true",
                        help="Refresh brain state without writing motor/urgent execution outputs")

    args = parser.parse_args()

    if args.action == "cycle":
        cmd_cycle(advisory_only=args.advisory_only)
    elif args.action == "daemon":
        cmd_daemon()
    elif args.action == "status":
        cmd_status()
    elif args.action == "awareness":
        cmd_awareness()
    elif args.action == "regions":
        print(f"\n{'='*60}")
        print(f"  🧠 BRAIN REGIONS")
        print(f"{'='*60}")
        for region_id, region in BRAIN_REGIONS.items():
            print(f"\n  [{region_id}]")
            print(f"     Name: {region['name']}")
            print(f"     Function: {region['function']}")
            if "inputs" in region:
                print(f"     Inputs ({len(region['inputs'])}):")
                for inp in region["inputs"]:
                    print(f"       - {inp['id']} ({inp['type']})")
            if "modules" in region:
                for m in region["modules"]:
                    print(f"       - {m}")
            if "outputs" in region:
                print(f"     Outputs:")
                for o in region["outputs"]:
                    print(f"       → {o}")
        print()
    elif args.action == "memory":
        memory = Hippocampus()
        limit = args.limit or 5
        if args.regime:
            results = memory.query_by_regime(args.regime, limit)
        elif args.outcome:
            results = memory.query_by_outcome(args.outcome, limit)
        elif args.signal:
            results = memory.query_by_signal(args.signal, limit)
        else:
            results = memory.memories[-limit:]
        print(f"\n  🧠 HIPPOCAMPUS QUERY: {len(results)} memories")
        for m in results[-5:]:
            mem_id = m.get("memory_id", "?")[:8]
            regime = m.get("regime", "?")
            if isinstance(regime, dict):
                regime = regime.get("regime", "?")
            fd = m.get("fused_direction", 0)
            outcome = m.get("outcome", "?")
            ts = m.get("ts", "")[:16] if m.get("ts") else "?"
            top = m.get("top_signals", [])
            print(f"     [{mem_id}] {ts} | regime={regime} | dir={fd:+.2f} | outcome={outcome}")
            if top:
                print(f"            signals: {', '.join(top[:3])}")
    elif args.action == "update-outcome":
        if not args.outcome:
            print("  Usage: python3 scripts/brain_cortex.py update-outcome --outcome win|loss|neutral [--cycle-id <id>]")
            return
        if args.outcome not in ("win", "loss", "neutral"):
            print(f"  Invalid outcome: {args.outcome}. Use win/loss/neutral.")
            return
        update_icm_outcome(args.outcome, args.cycle_id)


if __name__ == "__main__":
    main()
