// Earnings Volatility Strategy Module
// Implements short straddle and long calendar spread strategies for earnings events.
// This module provides utilities to evaluate and generate trade signals based on
// the predictor variables described in the video (term structure slope, 30d volume, IV/RV ratio).

use crate::types::*; // Assuming existing types for market data

/// Parameters for the earnings volatility model
#[derive(Debug, Clone)]
pub struct EarningsVolParams {
    /// Minimum negative term structure slope required (basis points)
    pub min_term_slope: f64,
    /// Minimum 30‑day average volume (in shares)
    pub min_avg_volume: u64,
    /// Minimum IV/RV ratio threshold
    pub min_iv_rv_ratio: f64,
    /// Kelly fraction for position sizing (0.0–1.0)
    pub kelly_fraction: f64,
    /// Strategy type: "straddle" or "calendar"
    pub strategy: String,
}

impl Default for EarningsVolParams {
    fn default() -> Self {
        EarningsVolParams {
            min_term_slope: -0.05,
            min_avg_volume: 1_000_000,
            min_iv_rv_ratio: 1.2,
            kelly_fraction: 0.065,
            strategy: "straddle".into(),
        }
    }
}

/// Evaluate a ticker for earnings volatility opportunity.
/// Returns `Some(TradeSignal)` if all filters pass.
pub fn evaluate_earnings(
    ticker: &str,
    data: &MarketData,
    params: &EarningsVolParams,
) -> Option<TradeSignal> {
    // 1. Term‑structure slope (near‑term vs 45‑day IV)
    if data.term_structure_slope > params.min_term_slope {
        return None;
    }
    // 2. 30‑day average volume
    if data.avg_volume_30d < params.min_avg_volume {
        return None;
    }
    // 3. IV/RV ratio
    if data.iv_rv_ratio < params.min_iv_rv_ratio {
        return None;
    }
    // Passed all filters – construct a signal
    Some(TradeSignal {
        ticker: ticker.to_string(),
        strategy: params.strategy.clone(),
        size: (params.kelly_fraction * data.equity * 0.01) as f64, // example sizing
        entry_date: data.next_earnings_date,
        notes: "Generated by earnings_volatility module".into(),
    })
}

/// Simple struct representing a generated trade signal.
#[derive(Debug, Clone)]
pub struct TradeSignal {
    pub ticker: String,
    pub strategy: String,
    pub size: f64,
    pub entry_date: chrono::NaiveDate,
    pub notes: String,
}

// Unit tests (run with `cargo test --package bill-core`)
#[cfg(test)]
mod tests {
    use super::*;
    use chrono::NaiveDate;

    #[test]
    fn test_evaluate_passes() {
        let data = MarketData {
            term_structure_slope: -0.10,
            avg_volume_30d: 2_000_000,
            iv_rv_ratio: 1.5,
            equity: 10_000.0,
            next_earnings_date: NaiveDate::from_ymd_opt(2026, 6, 15).unwrap(),
            ..Default::default()
        };
        let params = EarningsVolParams::default();
        let sig = evaluate_earnings("AAPL", &data, &params).expect("should produce signal");
        assert_eq!(sig.ticker, "AAPL");
        assert_eq!(sig.strategy, "straddle");
    }
}
